- name: Create ILM, Roles, Spaces, Templates
  hosts: [es_api]
  gather_facts: false
  vars:
    kibana_base_url: "http://{{ inventory_hostname }}.bcbsfl.com:5601"
    kibana_spaces_base_url: "{{kibana_base_url}}/api/spaces/space"
    es_base_url: "https://{{ inventory_hostname }}.bcbsfl.com:9200"
    ilm_policies_base_url: "{{es_base_url}}/_ilm/policy"
    ingest_pipelines_base_url: "{{es_base_url}}/_ingest/pipeline"
    rolemapping_base_url: "{{es_base_url}}/_security/role_mapping"
    roles_base_url: "{{es_base_url}}/_security/role"
    templates_base_url: "{{es_base_url}}/_template"
    api_username: "{{API_CREDENTIALS_USR}}"
    api_password: "{{API_CREDENTIALS_PSW}}"
  tasks:
    - name: Add Templates
      uri:
        url: "{{ templates_base_url }}/{{(item | basename).split(\".\")[0] | lower }}"
        url_username: "{{ api_username }}"
        url_password: "{{ api_password }}"
        method: PUT
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      no_log: False
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/index_templates -type f -name '*.json'"
      tags:
        - templates

    - name: Add Roles
      uri:
        url: "{{ roles_base_url }}/{{(item | basename).split(\".\")[0] | lower}}"
        url_username: "{{ api_username }}"
        url_password: "{{ api_password }}"
        method: PUT
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/roles -type f -name '*.json'"
      tags:
        - roles

    - name: Add Ingest Pipelines
      uri:
        url: "{{ ingest_pipelines_base_url }}/{{(item | basename).split(\".\")[0] | lower}}"
        url_username: "{{ api_username }}"
        url_password: "{{ api_password }}"
        method: PUT
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/ingest_pipelines -type f -name '*.json'"
      tags:
        - ingest_pipelines

    - name: Role Mappings
      uri:
        url: "{{ rolemapping_base_url }}/{{(item | basename).split(\".\")[0] | lower }}"
        url_username: "{{ api_username }}"
        url_password: "{{ api_password }}"
        method: PUT
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      no_log: False
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/role_mappings -type f -name '*.json'"
      tags:
        - role_mappings
        
    - name: Add Spaces
      uri:
        url: "{{ kibana_spaces_base_url }}"
        url_username: "{{ api_username }}"
        url_password: "{{ api_password }}"
        method: POST
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        headers:
          kbn-xsrf: true
        validate_certs: no
        status_code: 200, 409
      ignore_errors: yes
      no_log: False
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/kibana/spaces -type f -name '*.json'"
      tags:
        - spaces

    - name: Add ILM Policies
      uri:
        url: "{{ ilm_policies_base_url }}/{{(item | basename).split(\".\")[0] | lower}}"
        url_username: "{{ es_admin_user }}"
        url_password: "{{ es_admin_password }}"
        method: PUT
        body: "{{ lookup('file', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      run_once: true
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/ilm_policies -type f -name '*.json'"      
      no_log: False
      tags:
        - ilm

    - name: Add SLM Policies
      uri:
        url: "{{ slm_policies_base_url }}/{{(item | basename).split(\".\")[0] | lower}}"
        url_username: "{{ es_admin_user }}"
        url_password: "{{ es_admin_password }}"
        method: PUT
        body: "{{ lookup('template', '{{ item }}' ) }}"
        force_basic_auth: yes
        body_format: json
        validate_certs: no
        status_code: 200
      ignore_errors: yes
      run_once: true
      with_lines:
        - "find {{ playbook_dir }}/environments/{{env}}/**/slm_policies -type f -name '*.json.j2'"
      tags:
        - slm